version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: invoicymate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-schema:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot-service:
    build:
      context: ./bot-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: invoicymate
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres

  messenger-webhook:
    build:
      context: ./messenger-webhook
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: invoicymate
      DB_USER: postgres
      DB_PASSWORD: postgres
      BOT_SERVICE_URL: http://bot-service:3000
      PORT: 3001
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - bot-service

  pdf-service:
    build:
      context: ./pdf-service
      dockerfile: Dockerfile
    environment:
      PORT: 3002
    ports:
      - "3002:3002"

volumes:
  postgres_data:
